MIME-Version: 1.0
Received: by 10.76.143.70 with HTTP; Thu, 2 May 2013 09:52:18 -0700 (PDT)
In-Reply-To: <20130502081809.a48e592f496a79dd37635ca40a427343.44a8e6bbd0.wbe@email05.secureserver.net>
References: <20130502081809.a48e592f496a79dd37635ca40a427343.44a8e6bbd0.wbe@email05.secureserver.net>
Date: Thu, 2 May 2013 12:52:18 -0400
Delivered-To: randy.heydon@clockworklab.net
Message-ID: <CAG8SroZ530kOKpJMf6nbpLN9cm1Y6oRFzAXYveKBhwV+t0PcXA@mail.gmail.com>
Subject: Re: Function Keys Conference....
From: Randy Heydon <randy.heydon@clockworklab.net>
To: digital@centre3.com
Content-Type: multipart/alternative; boundary=e0cb4e38565eb3b39304dbbf0e91

--e0cb4e38565eb3b39304dbbf0e91
Content-Type: text/plain; charset=ISO-8859-1

Okay then.  Add on to the bio that I am a mechanical engineer with a
Bachelor's from the University of Waterloo and a Master's from Ryerson
University, where I simulated knee joints.  I now work at National Steel
Car, where much of my time goes to simulating railcars in many interesting
ways.

Hope that helps.

Randy


On Thu, May 2, 2013 at 11:18 AM, <digital@centre3.com> wrote:

> Hey Randy,
>           This sounds totally on the mark and I'm quite comfortable with
> it. Everything you've got there reads great to me.  The only thing I'm
> needing expanded on in the grant would be something in your bio about your
> educational background (certifications, where you graduated from and/or
> employment) then we should be good to go.  I appreciate this and am really
> excited and glad to have you be a part of the project.
>              Talk to you soon,
>                                  - Ian
>
>
>
>
>
>
>
>  -------- Original Message --------
> Subject: Re: Function Keys Conference....
> From: Randy Heydon <randy.heydon@clockworklab.net>
> Date: Tue, April 30, 2013 9:43 am
> To: digital@centre3.com
>
> Hi Ian. That talk I was telling you about, let's give it a working
> title of "Simulating Everything and its Consequences".
>
> I would cover some of the various ways modelling and simulation are
> used today, in engineering, architecture, computer graphics, science,
> whatever (there are a lot of ways). I would then focus on computer
> modelling and its capabilities and limitations (particularly things
> that can never be modelled). Finally, I would speculate about how
> progressions in technology and science will affect the world of
> modelling and simulation, and how that new modelling and simulation
> will affect everything else.
>
> Something like a bio: I am a mechanical engineer with experience in
> design, solid mechanics, finite element analysis, and multi-body
> simulation. I've built thousands of things inside computers because
> it's so expensive to build them in real life.
>
> Let me know if you need anything more. Sorry for taking so long; I
> promise I won't wait so long to compose the talk itself (especially
> since I have a lot of research to do!).
>
> Randy
>
>
> On Thu, 25 Apr 2013 09:58:03 -0700
> <digital@centre3.com> wrote:
>
> > Hey Randy,
> > Just wanted to drop you a line to talk about the Function
> > Keys Conference stuff. As I mentioned to you the other night I'm
> > presently putting together on a grant application to do the Function
> > Keys Conference again this year that's due on May 15th. I really
> > think you'd make a great speaker for it. It would be awesome to have
> > someone like yourself speaking about things and representing the
> > local DIY/hacker community. The purpose of the project is raise the
> > level of understanding and discussion within the community around the
> > impact of new contemporary technologies and ideas. The focus of the
> > talks is around the intersection of art, technology and digital
> > culture. Think of this project as something similar to a live TED
> > talks for Hamilton. You can visit the conference website at
> > www.functionkeys.ca for more details and to see last years presenter
> > information and videos. Should we be successful with the grant, this
> > years conference would take place over 3 to 4 days during mid
> > November 2013. All speakers would receive a professionally graded
> > academic/artist fee for their work (last year this was $600 for a
> > 30-40 min presentation with a 10-15 min audience Q & A), things would
> > appear on a website and in a catalog that would be distributed to
> > libraries, institutions and centres across the country. Again if you
> > are interested in presenting some of the projects or ideas you are
> > working on I'd really strongly encourage and welcome you to be apart
> > of things. As I mentioned before we are currently working on a
> > funding deadline for this project that is due really soon in
> > mid-May. If you are interested in being involved, for now all I'd
> > need from you is a few short sentences of what you'd like to speak
> > on, a title for your talk, and a very brief bio. I know it's
> > extremely short notice but if you are interested and could get these
> > things to me for by the middle of next week or sooner it would be
> > wonderful. Again nothing has to be written in stone and the ideas
> > can totally change between now and the time the presentation happens
> > at the conference. If you have any questions or concerns feel free to
> > drop me a line. We are also looking for ideas to do workshop and our
> > panel discussion topics so if you or anyone at Think Haus have any
> > suggestions feel free to send them my way. Thanks again for this,
> > - Ian
>
>

--e0cb4e38565eb3b39304dbbf0e91
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Okay then.=A0 Add on to the bio that I am a mechanical eng=
ineer with a Bachelor&#39;s from the University of Waterloo and a Master&#3=
9;s from Ryerson University, where I simulated knee joints.=A0 I now work a=
t National Steel Car, where much of my time goes to simulating railcars in =
many interesting ways.<br>
<br>Hope that helps.<br><br>Randy<br></div><div class=3D"gmail_extra"><br><=
br><div class=3D"gmail_quote">On Thu, May 2, 2013 at 11:18 AM,  <span dir=
=3D"ltr">&lt;<a href=3D"mailto:digital@centre3.com" target=3D"_blank">digit=
al@centre3.com</a>&gt;</span> wrote:<br>
<blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1p=
x #ccc solid;padding-left:1ex"><div><span style=3D"font-size:10pt;font-fami=
ly:Verdana"><div>Hey Randy,</div><div>=A0=A0=A0=A0=A0=A0=A0=A0=A0 This soun=
ds totally on the mark and I&#39;m quite comfortable with it. Everything yo=
u&#39;ve got there reads great to me.=A0 The only thing I&#39;m needing exp=
anded on in the grant would be something in your bio about your educational=
 background (certifications, where you graduated from and/or employment) th=
en we should be good to go.=A0 I appreciate this and am really excited and =
glad to have you be a part of the project.</div>
<div>=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0 Talk to you soon,</div><div>=A0=
=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=A0=
=A0=A0=A0=A0=A0=A0 - Ian </div><div><div class=3D"h5"><div><br></div><div><=
br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><=
br></div>
<blockquote style=3D"padding-left:8px;font-size:10pt;margin-left:8px;font-f=
amily:verdana;border-left:2px solid blue">
<div>
-------- Original Message --------<br>
Subject: Re: Function Keys Conference....<br>
From: Randy Heydon &lt;<a href=3D"mailto:randy.heydon@clockworklab.net" tar=
get=3D"_blank">randy.heydon@clockworklab.net</a>&gt;<br>
Date: Tue, April 30, 2013 9:43 am<br>
To: <a href=3D"mailto:digital@centre3.com" target=3D"_blank">digital@centre=
3.com</a><br>
<br>
Hi Ian.  That talk I was telling you about, let&#39;s give it a working<br>
title of &quot;Simulating Everything and its Consequences&quot;.<br>
<br>
I would cover some of the various ways modelling and simulation are<br>
used today, in engineering, architecture, computer graphics, science,<br>
whatever (there are a lot of ways).  I would then focus on computer<br>
modelling and its capabilities and limitations (particularly things<br>
that can never be modelled).  Finally, I would speculate about how<br>
progressions in technology and science will affect the world of<br>
modelling and simulation, and how that new modelling and simulation<br>
will affect everything else.<br>
<br>
Something like a bio:  I am a mechanical engineer with experience in<br>
design, solid mechanics, finite element analysis, and multi-body<br>
simulation.  I&#39;ve built thousands of things inside computers because<br=
>
it&#39;s so expensive to build them in real life.<br>
<br>
Let me know if you need anything more.  Sorry for taking so long; I<br>
promise I won&#39;t wait so long to compose the talk itself (especially<br>
since I have a lot of research to do!).<br>
<br>
Randy<br>
<br>
<br>
On Thu, 25 Apr 2013 09:58:03 -0700<br>
&lt;<a href=3D"mailto:digital@centre3.com" target=3D"_blank">digital@centre=
3.com</a>&gt; wrote:<br>
<br>
&gt; Hey Randy,<br>
&gt;         Just wanted to drop you a line to talk about the Function<br>
&gt; Keys Conference stuff.  As I mentioned to you the other night I&#39;m<=
br>
&gt; presently putting together on a grant application to do the Function<b=
r>
&gt; Keys Conference again this year that&#39;s due on May 15th.  I really<=
br>
&gt; think you&#39;d make a great speaker for it.  It would be awesome to h=
ave<br>
&gt; someone like yourself speaking about things and representing the<br>
&gt; local DIY/hacker community. The purpose of the project is raise the<br=
>
&gt; level of understanding and discussion within the community around the<=
br>
&gt; impact of new contemporary technologies and ideas. The focus of the<br=
>
&gt; talks is around the intersection of art, technology and digital<br>
&gt; culture.  Think of this project as something similar to a live TED<br>
&gt; talks for Hamilton.  You can visit the conference website at<br>
&gt; <a href=3D"http://www.functionkeys.ca" target=3D"_blank">www.functionk=
eys.ca</a> for more details and to see last years presenter<br>
&gt; information and videos. Should we be successful with the grant, this<b=
r>
&gt; years conference would take place over 3 to 4 days during mid<br>
&gt; November 2013. All speakers would receive a professionally graded<br>
&gt; academic/artist fee for their work (last year this was $600 for a<br>
&gt; 30-40 min presentation with a 10-15 min audience Q &amp; A), things wo=
uld<br>
&gt; appear on a website and in a catalog that would be distributed to<br>
&gt; libraries, institutions and centres across the country.  Again if you<=
br>
&gt; are interested in presenting some of the projects or ideas you are<br>
&gt; working on I&#39;d really strongly encourage and welcome you to be apa=
rt<br>
&gt; of things. As I mentioned before we are currently working on a<br>
&gt; funding deadline for this project that is due really soon in<br>
&gt; mid-May.  If you are interested in being involved, for now all I&#39;d=
<br>
&gt; need from you is a few short sentences of what you&#39;d like to speak=
<br>
&gt; on, a title for your talk, and a very brief bio. I know it&#39;s<br>
&gt; extremely short notice but if you are interested and could get these<b=
r>
&gt; things to me for by the middle of next week or sooner it would be<br>
&gt; wonderful.  Again nothing has to be written in stone and the ideas<br>
&gt; can totally change between now and the time the presentation happens<b=
r>
&gt; at the conference. If you have any questions or concerns feel free to<=
br>
&gt; drop me a line.  We are also looking for ideas to do workshop and our<=
br>
&gt; panel discussion topics so if you or anyone at Think Haus have any<br>
&gt; suggestions feel free to send them my way. Thanks again for this,<br>
&gt;                              - Ian<br>

</div>
</blockquote></div></div></span></div>
</blockquote></div><br></div>

--e0cb4e38565eb3b39304dbbf0e91--